name: Build and Push Multi-Architecture Image
#Publish GHCR
on:
  push:
    branches:
      - main
      - copilot/fix-0618b1b8-7dd8-485f-813d-6dbf7c0dd4cd
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and Push Multi-Architecture Image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Repository Name to Lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Architecture Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:latest
          platforms: linux/amd64,linux/arm64
